name: Bug Report
description: You think somethings is broken in the UI
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits
          required: true     
  - type: checkboxes
    attributes:
      label: I have to try to solve the issue myself
      description: Please do some basic debugging to see if extensions or configuration as the cause of the issue
      options:
        - label: I have tried disabling all extensions
          required: true
        - label: I have tried on a clean installation of webui
          required: true
        - label: The issue is caused by an extension but it is caused by a bug in webui
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, don't forget to "Upload Sysinfo" and "What browsers" and *provide screenshots if possible**
