name: Bug Report
description: You think somethings is broken in the UI
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits
          required: true
        - label: I have2
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, don't forget to "Upload Sysinfo" and "What browsers" and *provide screenshots if possible**
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: Tell us what happened in a very clear and simple way
      placeholder: |
        I tried to generate images using XYZ grid and it did not work
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step instructions on how to reproduce the bug
      placeholder: |
        1. Go to txt2img tab ...
        2. Select XYZ grid ...
        3. Set X axis type Sampler value DPM2, Euler 
        4. Press Generate
        5. you should see error message appears in console
        Screenshot or screen recording of the issue if necessary
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: What should have happened?
      description: Tell us what you think the normal behavior should be
      placeholder: |
        It should generate a grid of 2 images
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers do you use to access the UI ?
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Brave
        - Apple Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: misc
    attributes:
      label: Additional information
      description: Please provide us with any relevant additional info or context.
      placeholder: this was working in webui version 1.x.x
  - type: textarea
    id: sysinfo
    attributes:
      label: Sysinfo
      description: System info file, generated by WebUI. You can generate it in settings, on the Sysinfo page. Drag the file into the field to upload it. If you submit your report without including the sysinfo file, the report will be closed. If needed, review the report to make sure it includes no personal information you don't want to share. If you can't start WebUI, you can use --dump-sysinfo commandline argument to generate the file.
      placeholder: "\"Upload\" the Sysinfo as a file, don't past it hear."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Please provide **full** cmd/terminal logs from the moment you started UI to the end of it, after your bug happened. If it's very long, provide a link to pastebin or similar service.
      render: Shell
      placeholder: |
        venv "B:\stable-diffusion-webui\venv\Scripts\Python.exe"
        Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
        Version: v1.6.0
        Commit hash: 5ef669de080814067961f28357256e8fe27544f4
        Launching Web UI with arguments: --api --xformers
        Loading weights [31e35c80fc] from B:\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
        Running on local URL:  http://127.0.0.1:7860/

        To create a public link, set `share=True` in `launch()`.
        Creating model from config: B:\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
        Startup time: 5.8s (prepare environment: 1.2s, import torch: 1.6s, import gradio: 0.5s, setup paths: 0.4s, initialize shared: 0.1s, other imports: 0.3s, load scripts: 0.4s, create ui: 0.4s, gradio launch: 0.7s).
        Loading VAE weights from user metadata: B:\Stable Diffusion\Models\VAE\Stabilityaisd-vae-ft-ema\sdxl_vae 0.9 FP16 nan-fix.safetensors
        Applying attention optimization: xformers... done.
        Model loaded in 5.2s (load weights from disk: 0.9s, create model: 0.5s, apply weights to model: 2.3s, load VAE: 0.8s, calculate empty prompt: 0.6s).

        txt2img:
        X/Y/Z plot will create 0 images on 1 0x1 grid. (Total steps to process: 0)
        Unexpected error: Processing could not begin, you may need to refresh the tab or restart the service.
    validations:
      required: true
