name: Bug Report
description: You think somethings is broken in the UI
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits
          required: true     
  - type: checkboxes
    attributes:
      label: I have to try to solve the issue myself
      description: Please do some basic debugging to see if extensions or configuration as the cause of the issue
      options:
        - label: I have tried disabling all extensions
          required: true
        - label: I have tried on a clean installation of webui
          required: true
        - label: The issue is caused by an extension but it is caused by a bug in webui
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, don't forget to "Upload Sysinfo" and "What browsers" and *provide screenshots if possible**
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: Tell us what happened in a very clear and simple way
      placeholder: |
        I tried to generate images using XYZ grid and it did not work
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step instructions on how to reproduce the bug
      placeholder: |
        --- Example ---
        1. Go to txt2img tab ...
        2. Select XYZ grid ...
        3. Set X axis type Sampler value DPM2, Euler 
        4. Press Generate
        5. you should see error message appears in console
        Screenshot or screen recording of the issue if necessary
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: What should have happened?
      description: Tell us what you think the normal behavior should be
      placeholder: |
        --- Example ---
        It should generate a grid of 2 images
    validations:
      required: true

