name: date
"on":
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - extensions
    paths-ignore:
      - 'extensions/**.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'extensions/**.json'

jobs:
  date:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:

      - name: Get current date
        id: current-date
        run: echo "$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Warning wrong file
        run: |
          echo -e "::warning::${{ steps.current-date.outputs.msg }}"
