name: Update metadata

on:
    workflow_dispatch:
    schedule:
      - cron: '25 5 * * *'

permissions:
    contents: write

jobs:
    update-metadata:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false
        
        steps:
        - name: Checkout extensions
          uses: actions/checkout@v3
          with:
            ref: 'extensions'
            path: extensions

        - name: Checkout master
          uses: actions/checkout@v3
          with:
            ref: 'master'
            path: master

        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Update extension metadata
          run: python -B extensions/.github/scripts/update_metadata.py --max-thread 20 --github-token ${{ secrets.GITHUB_TOKEN }} --deploy-branch master
        
        - name: Get current date
          id: current-date
          run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

        - name: Commit - master
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Update metadata ${{ steps.current-date.outputs.date }}
            file_pattern: '*.json'
            repository: master
