name: Validate json

"on":
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - extensions
    paths:
      - 'extensions/**.json'
      - 'tags.json'
      - 'index.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'extensions/**.json'
      - 'tags.json'
      - 'index.json'

jobs:
  validate-json:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Setup python  
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Validate index
        run: python -B validate_json.py
