name: Warning marge into master

"on":
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - protected-branch

jobs:
  marge-into-master:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == true
    steps:
      - name: Warning marge into master
        run: |
          echo -e "::warning::This pull request directly merge into \"master\" branch, normally development happens on \"dev\" branch."
          exit 1
