name: Warning wrong file

"on":
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - extensions
    paths-ignore:
      - 'extensions/**.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'extensions/**.json'

jobs:
  wrong-file:
    runs-on: ubuntu-latest

    steps:
      - name: Warning wrong file
        run: |
          echo "::warning::Missing semicolon"
          exit 1
