name: Warning wrong file

"on":
  push:
    branches-ignore:
      - master
      - extensions
    paths-ignore:
      - 'extensions/**.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'extensions/**.json'

jobs:
  wrong-file:
    runs-on: ubuntu-latest

    steps:
      - name: Warning wrong file
        run:
          echo "::warning file={name},line={line},endLine={endLine},title={title}::{message}"
