name: Warning wrong file

"on":
  push:
    branches-ignore:
      - master
      - extensions
    paths-ignore:
      - 'extensions/**.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'extensions/**.json'

jobs:
  wrong-file:
    runs-on: ubuntu-latest

    steps:
      - name: Warning wrong file
        run: |
          echo You\'re probably doing something wrong
          echo Extension entries goes into \"extensions\" directory and must be in json format
          echo echo Don\'t modify or Add other files unless there\'s a special reason
          exit 1
